name: githun_account
description: A new Flutter project.

publish_to: // ...
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http:
  colour:
  url_launcher: ^6.1.5
  fluttertoast:
  flutter_svg:
  clipboard: ^0.1.3
  cached_network_image: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Segoe ui
      fonts:
        - asset: assets/fonts/SEGOEUI.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700